version: '3'
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  python_model:
    build:
      context: .
      dockerfile: Dockerfile.model
    volumes:
      - ./model:/model

volumes:
  mongo_data: